openapi: 3.0.0
info:
  title: Test API for GSoC project
  version: "1.0.0"
  description: |
    A cyclic dependency between other.yaml <--> cyclic_dependency.yaml
paths:
  /someMethod: # Needed, otherwise gnostic gives error
    get:
      operationId: someMethod
      responses:
        200:
          description: success
components:
  responses:
    Response:
      description: success
      content:
        application/json:
          schema:
            $ref: 'https://raw.githubusercontent.com/LorenzHW/gnostic-grpc/master/generator/testfiles/other.yaml#/components/schemas/Person'