openapi: 3.0.0
info:
  title: Test API for GSoC project
  version: "1.0.0"
  description: |
    This is a OpenAPI description for testing my GSoC project.

paths:
  ########################## PARAMETER ##########################
  /testInvalidPathParameter/{param1}:
    get:
      operationId: testInvalidPathParameter
      parameters:
        - name: param1
          in: query
          schema:
            type: array
            items:
              $ref: '#/components/parameters/ComponentExampleParameter'
      responses:
        200:
          description: success
components:
  schemas:
    ComponentsExampleSchema:
      properties:
        value1:
          type: string
        value2:
          type: integer
          format: int64
